spring:
  datasource:
    username: root
    password: 123456
    url:  jdbc:mysql://localhost:3306/forum?serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
